{{- if not .Values.secrets.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal-worker.secretName" . }}
  labels:
    {{- include "temporal-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
